default_language_version:
  python: python3

exclude: |
  (?x)^(
    [.]ipynb.*/.*|
    tests/.*|
    .*[.]ipynb
  )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    -   id: nbqa-black
        exclude: ^docs/
    -   id: nbqa-isort
        exclude: ^docs/
    -   id: nbqa-ruff
        exclude: ^docs/
    -   id: nbqa-mypy
        exclude: ^docs/

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: ^docs/

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        exclude: ^docs/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.270'
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        exclude: ^docs/

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        stages: [commit]
        types: [python]
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

